/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#4F46E5',
        'primary-hover': '#4338CA',
        'primary-tint': '#EEF2FF',
        'primary-container': '#4f46e5',
        'on-primary': '#ffffff',
        'on-primary-container': '#dad7ff',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'inverse-primary': '#c3c0ff',
        secondary: '#515f74',
        'secondary-container': '#d5e3fc',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#57657a',
        tertiary: '#7e3000',
        'tertiary-container': '#a44100',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffd2be',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#F7F8FA',
        'on-background': '#191c1e',
        surface: '#F7F8FA',
        'surface-bright': '#f8f9fb',
        'surface-dim': '#d9dadc',
        'surface-variant': '#e1e2e4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#edeef0',
        'surface-container-high': '#e7e8ea',
        'surface-container-highest': '#e1e2e4',
        'on-surface': '#0F172A',
        'on-surface-variant': '#475569',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f3',
        outline: '#E5E7EB',
        'outline-variant': '#E5E7EB',
        'surface-tint': '#4d44e3',
        muted: '#94A3B8',
        // Semantic
        success: '#16A34A',
        'success-bg': '#DCFCE7',
        warning: '#D97706',
        'warning-bg': '#FEF3C7',
        danger: '#DC2626',
        'danger-bg': '#FEE2E2',
        info: '#0EA5E9',
        'info-bg': '#E0F2FE',
        // Product colors
        'estate-color': '#4F46E5',
        'logistics-color': '#0EA5E9',
        'school-color': '#16A34A',
        'hospital-color': '#DC2626',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'page-title': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'section-heading': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'stat-value': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.04em' }],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'sidebar': '240px',
        'topbar': '56px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(16,24,40,.06), 0 1px 3px rgba(16,24,40,.10)',
        dropdown: '0 10px 15px -3px rgba(0,0,0,.1), 0 4px 6px -4px rgba(0,0,0,.1)',
        modal: '0 20px 60px -10px rgba(0,0,0,.25)',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.5s infinite linear',
        'slide-in-right': 'slide-in-right 0.25s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
      },
    },
  },
  plugins: [],
};
